import type { Dataset, ValidationReport, AnomalyLog, DatasetSpecification } from '../types';

export function downloadFile(content: string, fileName: string, contentType: string): void {
  const blob = new Blob([content], { type: contentType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = fileName;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportDatasetToCsv(dataset: Dataset): void {
  if (dataset.records.length === 0) return;

  const columns = dataset.specification.schema.map(c => c.name);
  const headers = columns.join(',');

  const rows = dataset.records.map(record => {
    return columns.map(col => {
      const val = record[col];
      if (val === null || val === undefined) return '';
      if (typeof val === 'string') {
        // Escape quotes
        const escaped = val.replace(/"/g, '""');
        return `"${escaped}"`;
      }
      return String(val);
    }).join(',');
  });

  const csvContent = [headers, ...rows].join('\n');
  downloadFile(csvContent, `${dataset.name}_${dataset.rowCount}_rows.csv`, 'text/csv;charset=utf-8;');
}

export function exportSpecificationJson(spec: DatasetSpecification): void {
  const jsonContent = JSON.stringify(spec, null, 2);
  downloadFile(jsonContent, `${spec.name}_specification.json`, 'application/json');
}

export function exportValidationReportJson(report: ValidationReport, datasetName: string): void {
  const jsonContent = JSON.stringify(report, null, 2);
  downloadFile(jsonContent, `${datasetName}_validation_report.json`, 'application/json');
}

export function exportValidationReportMarkdown(report: ValidationReport, dataset: Dataset): void {
  const lines: string[] = [
    `# SyntheticLab Validation Audit Report`,
    ``,
    `**Dataset Name**: \`${dataset.name}\``,
    `**Dataset ID**: \`${dataset.id}\``,
    `**Domain**: \`${dataset.domain}\``,
    `**Total Rows**: ${dataset.rowCount.toLocaleString()}`,
    `**Seed**: \`${dataset.seed}\``,
    `**Validated At**: ${report.validatedAt}`,
    `**Overall Status**: **${report.overallStatus}**`,
    `**Compliance Rate**: **${report.complianceRate}%** (${report.passedChecks}/${report.totalChecks} checks passed)`,
    ``,
    `---`,
    ``,
    `## Validation Measurements`,
    ``,
    `| Requirement / Metric | Target | Actual | Deviation | Tolerance | Status |`,
    `|:---|:---:|:---:|:---:|:---:|:---:|`,
  ];

  report.checks.forEach(chk => {
    const devSign = chk.deviation > 0 ? `+${chk.deviation}` : `${chk.deviation}`;
    lines.push(
      `| **${chk.metric}** | ${chk.target}${chk.unit} | ${chk.actual}${chk.unit} | ${devSign}${chk.unit} | ±${chk.tolerance}${chk.unit} | \`${chk.status}\` |`
    );
  });

  lines.push(``);
  lines.push(`## Statistical Moments`);
  lines.push(``);
  lines.push(`- **Mean Amount**: $${report.statisticalMetrics.meanAmount?.toLocaleString() ?? 'N/A'}`);
  lines.push(`- **Std Deviation**: $${report.statisticalMetrics.stdDevAmount?.toLocaleString() ?? 'N/A'}`);
  lines.push(`- **Min / Max Range**: $${report.statisticalMetrics.minAmount} — $${report.statisticalMetrics.maxAmount}`);
  lines.push(`- **Weekend Distribution**: ${report.statisticalMetrics.weekendTransactions?.toLocaleString()} weekend rows vs ${report.statisticalMetrics.weekdayTransactions?.toLocaleString()} weekday rows`);
  lines.push(``);
  lines.push(`---`);
  lines.push(`*Generated by SyntheticLab deterministic data verification engine.*`);

  const mdContent = lines.join('\n');
  downloadFile(mdContent, `${dataset.name}_validation_audit.md`, 'text/markdown;charset=utf-8;');
}

export function exportAnomalyLogCsv(anomalyLogs: AnomalyLog[], datasetName: string): void {
  const headers = ['id', 'rowId', 'type', 'column', 'originalValue', 'injectedValue', 'severity', 'reason', 'ruleFormula', 'timestamp'];
  const rows = anomalyLogs.map(log => {
    return [
      `"${log.id}"`,
      log.rowId,
      `"${log.type}"`,
      `"${log.column}"`,
      `"${String(log.originalValue ?? '').replace(/"/g, '""')}"`,
      `"${String(log.injectedValue ?? '').replace(/"/g, '""')}"`,
      `"${log.severity}"`,
      `"${log.reason.replace(/"/g, '""')}"`,
      `"${log.ruleFormula.replace(/"/g, '""')}"`,
      `"${log.timestamp}"`
    ].join(',');
  });

  const csvContent = [headers.join(','), ...rows].join('\n');
  downloadFile(csvContent, `${datasetName}_anomaly_audit_log.csv`, 'text/csv;charset=utf-8;');
}
